# Generated by Django 4.2.8 on 2024-03-20 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0002_company_alter_movie_title_movie_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="films.company",
            ),
        ),
    ]
