# Generated by Django 4.2.8 on 2024-02-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=255, null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="surname",
            field=models.CharField(max_length=255, null=True, verbose_name="Surname"),
        ),
    ]
