# Generated by Django 4.2.8 on 2024-02-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_name_alter_user_surname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(default=0, max_length=255, verbose_name="Name"),
        ),
    ]
