# Generated by Django 4.2.8 on 2024-02-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(null=True, verbose_name="Birthday"),
        ),
    ]
